ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: false           # Doit être false pour utiliser GPS
    publish_tf: true
    publish_acceleration: false
    map_frame: map
    odom_frame: odom
    world_frame: odom

    # Configuration GPS
    navsat0: /gps/fix
    navsat0_config: [true, true, true,     # Position (lat, lon, alt)
                     false, false, false,  # Vitesse linéaire
                     false, false, false,  # Orientation
                     false, false, false]  # Vitesse angulaire
    navsat0_delay: 0.0
    navsat0_gps_use: true
    datum: [49.230525, 17.657223, 251.0]  # Point de référence (utilisez votre premier point de mission)
    navsat0_queue_size: 10

    # Configuration IMU
    imu0: /imu_data
    imu0_config: [false, false, false,   # Position
                  false, false, false,    # Orientation
                  false, false, false,   # Vitesse linéaire
                  true,  true,  true,    # Vitesse angulaire
                  false, false, false]    # Accélération
    imu0_queue_size: 10

    # Process noise covariance
    process_noise_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.01, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.01]

    initial_state: [0.0, 0.0, 0.0,   # Position (x, y, z)
                    0.0, 0.0, 0.0,   # Orientation (roll, pitch, yaw)
                    0.0, 0.0, 0.0,   # Vitesse linéaire (vx, vy, vz)
                    0.0, 0.0, 0.0,   # Vitesse angulaire (vroll, vpitch, vyaw)
                    0.0, 0.0, 0.0]   # Accélération (ax, ay, az)
    
    # Debug
    debug: true
    print_diagnostics: true