ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true           # We consider horizontal XY + yaw (2D)
    publish_tf: true
    publish_acceleration: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    navsat0: /gps/fix
    navsat0_config: [false, false, false,
                   false, false, false,
                   true,  true,  true,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10

    imu0: /imu_data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_queue_size: 10

    # Process noise covariance params
    process_noise_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.05, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.05, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
